"WebApp.exe" (CoreCLR: DefaultDomain). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Private.CoreLib.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Temp\ispp21\CourseProject\ArhReestr\WebApp\bin\Debug\net8.0\WebApp.dll". Символы загружены.
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Runtime.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\web tools\projectsystem\net7.0\Microsoft.WebTools.ApiEndpointDiscovery.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Linq.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Collections.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\SDK\9.0.300\DotnetTools\dotnet-watch\9.0.300-rtm.25252.6\tools\net9.0\any\middleware\Microsoft.AspNetCore.Watch.BrowserRefresh.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\Microsoft\Web Tools\Browser Link\Microsoft.WebTools.BrowserLink.Net.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\hotreload\Microsoft.Extensions.DotNetDeltaApplier.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.IO.Pipes.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Console.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Threading.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Runtime.InteropServices.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Threading.Overlapped.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Security.AccessControl.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Security.Principal.Windows.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Security.Claims.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Runtime.Loader.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Hosting.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Collections.Concurrent.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.DependencyInjection.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Logging.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Diagnostics.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Configuration.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Http.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Routing.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.ComponentModel.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Features.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Temp\ispp21\CourseProject\ArhReestr\WebApp\bin\Debug\net8.0\DataLayer.dll". Символы загружены.
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Temp\ispp21\CourseProject\ArhReestr\WebApp\bin\Debug\net8.0\Microsoft.EntityFrameworkCore.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Data.Common.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Configuration.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Primitives.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Identity.Core.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Identity.Stores.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Identity.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Authentication.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Authentication.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Authorization.Policy.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Authorization.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Components.Authorization.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Components.Server.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Components.Endpoints.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Hosting.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.HttpsPolicy.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.StaticFiles.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Antiforgery.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Components.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Diagnostics.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
Шаг с заходом: обход кода, не являющегося кодом пользователя "Program.<>c__DisplayClass0_0..ctor"
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Hosting.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Hosting.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Configuration.EnvironmentVariables.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.FileProviders.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.FileProviders.Physical.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Configuration.FileExtensions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Options.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Logging.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Diagnostics.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Diagnostics.DiagnosticSource.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Configuration.Binder.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Configuration.Json.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Memory.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.IO.FileSystem.Watcher.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.ComponentModel.Primitives.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\Microsoft.Win32.Primitives.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Text.Json.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Text.Encoding.Extensions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Configuration.UserSecrets.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Logging.EventLog.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Logging.Configuration.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Options.ConfigurationExtensions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Logging.Console.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Logging.Debug.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Logging.EventSource.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Diagnostics.Tracing.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.DependencyInjection.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Server.Kestrel.Core.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Server.Kestrel.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Net.Quic.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Net.Sockets.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Net.Primitives.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Server.IIS.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Server.IISIntegration.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.FileProviders.Composite.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Text.Encodings.Web.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Runtime.Intrinsics.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Numerics.Vectors.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Private.Uri.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Http.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Mvc.ApiExplorer.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Mvc.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Mvc.Core.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Connections.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.ObjectPool.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.HostFiltering.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.HttpOverrides.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Routing.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.ObjectModel.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Authentication.Core.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.DataProtection.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.DataProtection.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Cryptography.Internal.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.WebEncoders.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Authentication.Cookies.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Components.Web.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.JSInterop.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.SignalR.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.SignalR.Core.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Caching.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.SignalR.Common.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.WebSockets.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Http.Connections.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.SignalR.Protocols.Json.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Threading.Thread.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\System.Diagnostics.EventLog.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Collections.Specialized.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.ComponentModel.TypeConverter.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Threading.ThreadPool.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\System.IO.Pipelines.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Collections.Immutable.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Temp\ispp21\CourseProject\ArhReestr\WebApp\bin\Debug\net8.0\MySql.EntityFrameworkCore.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Temp\ispp21\CourseProject\ArhReestr\WebApp\bin\Debug\net8.0\Microsoft.EntityFrameworkCore.Relational.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Temp\ispp21\CourseProject\ArhReestr\WebApp\bin\Debug\net8.0\MySql.Data.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Linq.Expressions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Temp\ispp21\CourseProject\ArhReestr\WebApp\bin\Debug\net8.0\Microsoft.EntityFrameworkCore.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Transactions.Local.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Text.RegularExpressions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Reflection.Emit.Lightweight.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Reflection.Emit.ILGeneration.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Reflection.Primitives.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.Caching.Memory.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.ComponentModel.Annotations.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Net.NetworkInformation.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Temp\ispp21\CourseProject\ArhReestr\WebApp\bin\Debug\net8.0\System.Security.Permissions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Temp\ispp21\CourseProject\ArhReestr\WebApp\bin\Debug\net8.0\System.Configuration.ConfigurationManager.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Diagnostics.Process.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Xml.ReaderWriter.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Private.Xml.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Net.WebClient.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Security.Cryptography.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Net.NameResolution.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Net.Security.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Collections.NonGeneric.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Text.Encoding.CodePages.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\Microsoft.Win32.Registry.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Http.Features.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.WebUtilities.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.FileProviders.Embedded.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Xml.XDocument.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Private.Xml.Linq.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Http.Extensions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Metadata.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.IO.MemoryMappedFiles.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Runtime.Extensions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Http.Connections.Common.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "Anonymously Hosted DynamicMethods Assembly". 
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Threading.Channels.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Extensions.FileSystemGlobbing.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Runtime.Numerics.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Diagnostics.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.Net.Http.Headers.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Net.Http.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:7061
Microsoft.Hosting.Lifetime: Information: Now listening on: http://localhost:5104
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development
Microsoft.Hosting.Lifetime: Information: Content root path: C:\Temp\ispp21\CourseProject\ArhReestr\WebApp
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Net.WebSockets.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Threading.Tasks.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Html.Abstractions.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Linq.Queryable.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.16\Microsoft.AspNetCore.Components.Forms.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
"WebApp.exe" (CoreCLR: clrhost). Загружено "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.16\System.Runtime.Serialization.Primitives.dll". Загрузка символов пропущена. Модуль оптимизирован, включен параметр отладчика "Только мой код".
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT `d`.`id`, `d`.`name`
FROM `Districts` AS `d`
ORDER BY `d`.`name`
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT `r`.`id`, `r`.`name`
FROM `RealEstateTypes` AS `r`
ORDER BY `r`.`name`
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (5ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT `t`.`id`, `t`.`agentId`, `t`.`area`, `t`.`createdAt`, `t`.`deletedAt`, `t`.`description`, `t`.`districtId`, `t`.`floor`, `t`.`hasBalcony`, `t`.`houseId`, `t`.`price`, `t`.`rooms`, `t`.`typeId`, `d`.`id`, `d`.`name`, `r0`.`id`, `r0`.`name`, `u`.`id`, `u`.`createdAt`, `u`.`deletedAt`, `u`.`email`, `u`.`emailVerified`, `u`.`firstName`, `u`.`lastName`, `u`.`middleName`, `u`.`passwordHash`, `u`.`phone`, `u`.`phoneVerified`, `u`.`roleId`, `h`.`id`, `h`.`buildingYear`, `h`.`hasElevator`, `h`.`hasParking`, `h`.`latitude`, `h`.`longitude`, `h`.`number`, `h`.`streetId`, `h`.`totalFloors`, `s`.`id`, `s`.`name`, `r1`.`id`, `r1`.`deletedAt`, `r1`.`fileName`, `r1`.`filePath`, `r1`.`isPrimary`, `r1`.`realEstateId`
FROM (
    SELECT `r`.`id`, `r`.`agentId`, `r`.`area`, `r`.`createdAt`, `r`.`deletedAt`, `r`.`description`, `r`.`districtId`, `r`.`floor`, `r`.`hasBalcony`, `r`.`houseId`, `r`.`price`, `r`.`rooms`, `r`.`typeId`
    FROM `RealEstate` AS `r`
    WHERE `r`.`deletedAt` IS NULL
    ORDER BY `r`.`price`
    LIMIT @__p_0
) AS `t`
INNER JOIN `Districts` AS `d` ON `t`.`districtId` = `d`.`id`
INNER JOIN `RealEstateTypes` AS `r0` ON `t`.`typeId` = `r0`.`id`
INNER JOIN `Users` AS `u` ON `t`.`agentId` = `u`.`id`
INNER JOIN `Houses` AS `h` ON `t`.`houseId` = `h`.`id`
INNER JOIN `Streets` AS `s` ON `h`.`streetId` = `s`.`id`
LEFT JOIN `RealEstatePhotos` AS `r1` ON `t`.`id` = `r1`.`realEstateId`
ORDER BY `t`.`price`, `t`.`id`, `d`.`id`, `r0`.`id`, `u`.`id`, `h`.`id`, `s`.`id`
